version: "3.9"

services:
  linux:
    build:
      context: .
    platform: linux/x86_64
    container_name: linux_docker_goldrush
#    ports:
#      - "8004:80"
    volumes:
      - ./commands/deploy_kohls.sh:/app/deploy_kohls.sh
      - ./commands/deploy_default_us_east_1.sh:/app/deploy_default_us_east_1.sh
      - ./commands/deploy_prod_eu_west_1.sh:/app/deploy_prod_eu_west_1.sh
      - ./commands/deploy_prod_us_east_1.sh:/app/deploy_prod_us_east_1.sh
      - ./commands/clean_new_repository.sh:/app/clean_new_repository.sh
      - ./commands/deploy_to_whole_fleet.sh:/app/deploy_to_whole_fleet.sh
      - ./commands/check_env_file.sh:/app/check_env_file.sh
      - ./commands/git_process.sh:/app/git_process.sh
      - ./.env:/app/.env
    command: tail -f /dev/null